spring:
  application:
    name: authorization-server
  config:
    import:
    - "optional:configserver:http://user:1234@localhost:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: authServerPass99$
  sql:
    init:
      mode: never # Set it with the value "always" once to create the database, after return it to "never"
